
import './global.css';
import Header from './shared/widget/header';
import {Poppins,Roboto} from "next/font/google"

  export const metadata = {
    title: 'Ecommerce_',
    description: 'Generated by ME@',
  };


  const roboto = Roboto({
    subsets: ["latin"],
    weight: "400", // or specify desired weight
    variable: "--font-roboto",
  });

  const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "700"],
    variable: "--font-poppins",
  });


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <Header />
        {children}
        </body>
    </html>
  );
}
