

import type { Metadata } from "next"; 
import { Providers } from "@packages/utils"

import { Poppins, Roboto } from "next/font/google";
import './user-ui.css';

import ClientLayout from './shared/widget/headerProvider';
// --REACT SCAN---------------
import Script from "next/script";

export const metadata: Metadata = {
  title: 'Ecommerce_',
  description: '🤷‍♂️🤷‍♂️🤷 Generated by -- ME@ -- 🤷‍♂️🤷‍♂️🤷',
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "700"],
  variable: "--font-poppins",
});



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html data-scroll-behavior="smooth" lang="en">
      <head>
        <Script
          src="//unpkg.com/react-scan/dist/auto.global.js"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <Providers>
          
          <ClientLayout> 
            {children}
          </ClientLayout>
          
        </Providers>
      </body>
    </html>
  );
}