// app/layout.tsx
import './global.css';
import Providers from '../../../utils/providers';
import { Poppins, Roboto } from "next/font/google";
import Header from './shared/widget/header';
import { headers } from 'next/headers';

export const metadata = {
  title: 'Ecommerce_',
  description: '🤷‍♂️🤷‍♂️🤷 Generated by ME@ 🤷‍♂️🤷‍♂️🤷',
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "700"],
  variable: "--font-poppins",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = await headers();
  const pathname = headersList.get('x-pathname') || '/';

  // Pages where header/hero should NOT show
  const hideHeaderRoutes = ['/login', '/signup', '/forgot-password', '/product*'];
  const showHeader = !hideHeaderRoutes.some(route => pathname.startsWith(route));

  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <Providers>
          {/* ✅ Only show Header + Hero on non-auth pages */}
          {showHeader && (
            <>
              <Header />
            </>
          )}
          {children}
        </Providers>
      </body>
    </html>
  );
}