import { Providers } from '@packages/utils';
import { Poppins } from 'next/font/google';
import { Shadows_Into_Light } from 'next/font/google';
import '../seller-UI.css';
import type { Metadata } from 'next';

// --REACT SCAN---------------
import Script from 'next/script';

export const metadata: Metadata = {
  metadataBase: new URL('http://localhost:4000'),
  title: 'Ecommerce_',
  description: '🤷‍♂️🤷‍♂️🤷 Generated by -- ME@ -- 🤷‍♂️🤷‍♂️🤷',
};

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '300', '400', '600', '700'],
});

const shadowsIntoLight = Shadows_Into_Light({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-shadows-into-light',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-scroll-behavior="smooth" lang="en">
      <head>
        <link rel="preconnect" href="https://ik.imagekit.io" />
        <link rel="dns-prefetch" href="https://ik.imagekit.io" />

        <Script
          src="//unpkg.com/react-scan/dist/auto.global.js"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </head>

      <body
        className={`min-h-screen font-sans antialiased ${poppins.variable} ${shadowsIntoLight.variable}`}
        suppressHydrationWarning
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
