import './global.css';
import Providers from './providers';

export const metadata = {
  title: 'Ecommerce_',
  description: '🤷‍♂️🤷‍♂️🤷 Generated by ME@ 🤷‍♂️🤷‍♂️🤷',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>

          {children}

        </Providers>
      </body>
    </html>
  );
}
