
import './global.css';
import Providers from './providers';
import { Poppins } from 'next/font/google';

export const metadata = {
  title: 'Ecommerce_',
  description: '🤷‍♂️🤷‍♂️🤷 Generated by ME@ 🤷‍♂️🤷‍♂️🤷',
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen Übg-s1ate-9@0 font-sans antialiased ${poppins.className}`}>
        <Providers>

          {children}

        </Providers>
      </body>
    </html>
  );
}
